POST http://localhost:3079/register
Content-Type: application/json

{
    "username" : "Mekala2526",
    "name" : "MadhuKiran",
    "password" : "madhu_123",
    "gender" : "male",
    "location" : "NTPC"
}
###

POST http://localhost:3079/login/
Content-Type: application/json

{
    "username" : "Mekala2526",
    "password" : "madhu_123"
}
###

PUT http://localhost:3079/change-password
Content-Type: application/json

{
    "username" : "Mekala2526",
    "oldPassword" : "madhu_123",
    "newPassword" : "yadav_2526"
}